name: Test Issue Trigger

on:
  issues:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Issue event triggered for ${{ github.event.issue.number }}"